d <- read.table("feature-reversal.dat")
names(d) <- c("t","cs","out")
A <- subset( d, cs=="A" )
B <- subset( d, cs=="B" )
AB <- subset( d, cs=="AB" )
X <- subset( d, cs=="X" )
pdf( "feature-reversal.pdf", height=5, width=5 )
plot(A$t, A$out, type="l", xlab="t", xlim=c(1,max(d$t)),
     ylab="output", ylim=c(0,1) )
lines( X$t, X$out, col=2 )
lines( AB$t, AB$out, col=3 )
lines( B$t, B$out, col=4 )
legend("topright",legend=c("A","X","AB","B"), bty="n",
       lty=1, col=c(1,2,3,4) )
dev.off()
